worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
    }

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        root /var/www/html/awroberts/awroberts-media;
        index index.html;

        location /healthz {
            return 200;
        }

        location ~* \.m3u8$ {
            add_header Cache-Control "public, max-age=60";
            try_files $uri =404;
        }

        location ~* \.ts$ {
            add_header Cache-Control "public, max-age=31536000, immutable";
            try_files $uri =404;
        }

        location /stream/ {
            alias /usr/share/nginx/html/stream/;
        }

        location / {
            return 404;
        }
    }
}
