replicaCount: 1

image:
  repository: awroberts
  tag: latest
  pullPolicy: Never

traefik:
  hostnames:
    - awroberts.co.uk
    - www.awroberts.co.uk
  tls:
    secretName: awroberts-tls
  hsts:
    maxAge: 31536000
    includeSubdomains: true

gateway:
  name: awroberts-web-deploy-gateway
  namespace: traefik

stream:
  pathPrefix: /stream/

volume:
  hostPath: /var/www/html/awroberts
  mountPath: /usr/share/nginx/html

containerPort: 80

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 2
  periodSeconds: 5

service:
  type: ClusterIP
  port: 80
  portName: http
  protocol: TCP

autoscaling:
  enabled: false

backgroundVideo:
  source: "/usr/share/nginx/html/awroberts-media/hls/stream.m3u8"

  ffmpeg:
    image:
      repository: jrottenberg/ffmpeg
      tag: "8-alpine"
      pullPolicy: IfNotPresent

  hls:
    segmentDuration: 2
    liveWindow: 10
    liveSegmentPrefix: "live_"
    outputDir: "/usr/share/nginx/html/stream"

  resources:
    ffmpeg:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
