replicaCount: 1

image:
  repository: awroberts
  tag: latest
  pullPolicy: Never

traefik:
  hostnames:
    - awroberts.co.uk
    - www.awroberts.co.uk
  tls:
    secretName: awroberts-tls
  hsts:
    maxAge: 31536000
    includeSubdomains: true

volume:
  hostPath: /var/www/html/awroberts/awroberts-media
  mountPath: /usr/share/nginx/html/awroberts-media

containerPort: 80

resources: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 2
  periodSeconds: 5

service:
  type: LoadBalancer
  port: 80
  annotations:
    metallb.io/address-pool: awroberts-pool

autoscaling:
  enabled: false
