replicaCount: 1

image:
  repository: docker.io/library/awroberts
  tag: latest
  pullPolicy: Never

traefik:
  hostnames:
    - awroberts.co.uk
    - www.awroberts.co.uk
  tls:
    secretName: awroberts-tls
  hsts:
    maxAge: 31536000
    includeSubdomains: true

gateway:
  name: awroberts-web-deploy-gateway
  namespace: awroberts
  className: traefik
  hostnames:
    root: awroberts.co.uk
    wildcard: "*.awroberts.co.uk"

stream:
  pathPrefix: /stream

media:
  hostPath: /var/www/html/awroberts/awroberts-media
  mountPath: /var/www/html/awroberts/awroberts-media

assets:
  fallbackImage: background-poster.png
  fallbackImagePublicPath: /fallback/background.png
  fallbackCacheControl: "public, max-age=604800"

  fontFile: CURWENFONT.ttf
  fontPublicPath: /awroberts-media/CURWENFONT.ttf
  fontCacheControl: "public, max-age=31536000, immutable"

  publicPath: /assets
  mountPath: /usr/share/nginx/html/assets

nginx:
  workerProcesses: 1
  workerConnections: 1024
  keepaliveTimeout: 65
  listenPort: 80
  serverName: "_"
  root: /usr/share/nginx/html
  index: index.html

  mimeTypes:
    ttf: "font/ttf"
    otf: "font/otf"
    woff: "font/woff"
    woff2: "font/woff2"

containerPort: 80

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 2
  periodSeconds: 5

service:
  type: ClusterIP
  port: 80
  portName: http
  protocol: TCP

autoscaling:
  enabled: false

backgroundVideo:
  source: "/srv/input-hls/stream.m3u8"

  ffmpeg:
    image:
      repository: jrottenberg/ffmpeg
      tag: "8.1-scratch"
      pullPolicy: IfNotPresent

  nginx:
    image:
      repository: docker.io/library/background-video
      tag: latest
      pullPolicy: Never

    volume:
      name: hls-output
      hostPath: /var/www/html/awroberts/awroberts-media

  desktop:
    enabled: true
    scale: "3840:-1"
    bitrate: "8000k"
    maxrate: "10000k"
    bufsize: "20000k"
    preset: "veryfast"

  hls:
    segmentDuration: 2
    liveWindow: 10
    liveSegmentPrefix: "live_"
    outputDir: "/var/www/html/awroberts/awroberts-media/stream"

  resources:
    ffmpeg:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    nginx:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi

  mobile:
    enabled: true
    scale: "1280:-1"
    bitrate: "900k"
    maxrate: "1000k"
    bufsize: "1500k"
    audioBitrate: "128k"
    liveWindow: 10
    outputDir: "/var/www/html/awroberts/awroberts-media/stream/mobile"
    segmentPrefix: "mobile_"
    preset: "fast"
