apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.fullname" . }}
  labels:
    {{- include "awroberts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "awroberts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "awroberts.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          volumeMounts:
            - name: media-volume
              mountPath: {{ .Values.media.mountPath }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

      volumes:
        - name: media-volume
          hostPath:
            path: {{ .Values.media.hostPath }}
            type: Directory
