apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "awroberts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "awroberts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "awroberts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/nginx-config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ include "awroberts.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx.listenPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.nginx.listenPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.nginx.listenPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: media-volume
              mountPath: {{ .Values.media.mountPath }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "awroberts.name" . }}-nginx
        - name: media-volume
          hostPath:
            path: {{ .Values.media.hostPath }}
            type: Directory
