apiVersion: v1
kind: ConfigMap
metadata:
  name: awroberts-web-nginx
data:
  nginx.conf: |
    worker_processes {{ .Values.nginx.workerProcesses }};

    events {
        worker_connections {{ .Values.nginx.workerConnections }};
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        types {
            {{ .Values.nginx.mimeTypes.ttf }} ttf;
            {{ .Values.nginx.mimeTypes.otf }} otf;
            {{ .Values.nginx.mimeTypes.woff }} woff;
            {{ .Values.nginx.mimeTypes.woff2 }} woff2;
        }

        sendfile on;
        keepalive_timeout {{ .Values.nginx.keepaliveTimeout }};

        server {
            listen {{ .Values.nginx.listenPort }};
            listen [::]:{{ .Values.nginx.listenPort }};
            server_name "{{ .Values.nginx.serverName }}";

            root "{{ .Values.nginx.root }}";
            index "{{ .Values.nginx.index }}";

            location "{{ .Values.livenessProbe.httpGet.path }}" {
                return 200;
            }

            location ~* \.json$ {
                default_type application/json;
                try_files $uri =404;
            }

            location = "{{ .Values.assets.fallbackImagePublicPath }}" {
                alias "{{ .Values.media.mountPath }}/{{ .Values.assets.fallbackImage }}";
                add_header Cache-Control "{{ .Values.assets.fallbackCacheControl }}" always;
            }

            location = "{{ .Values.assets.fontPublicPath }}" {
                alias "{{ .Values.media.mountPath }}/{{ .Values.assets.fontFile }}";
                add_header Cache-Control "{{ .Values.assets.fontCacheControl }}" always;
            }

            location {{ .Values.assets.publicPath }}/ {
                alias {{ .Values.assets.mountPath }}/;
                add_header Cache-Control "public, max-age=31536000";
            }

            location / {
                try_files $uri $uri/ "/{{ .Values.nginx.index }}";
            }
        }
    }
