apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: no-cache-hls
  namespace: traefik
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "no-store, no-cache, must-revalidate, max-age=0"
      Pragma: "no-cache"
      Expires: "0"
