apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: static-cache
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "public, max-age=31536000, immutable"
