apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "awroberts-web.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    port: 443
    permanent: true