apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "awroberts-web.fullname" . }}-security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    stsSeconds: {{ .Values.traefik.hsts.maxAge }}
    stsIncludeSubdomains: {{ .Values.traefik.hsts.includeSubdomains }}
    forceSTSHeader: true