apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: block-bad-paths
  namespace: {{ .Values.gateway.namespace }}
spec:
  redirectRegex:
    regex: "^/(xmlrpc\\.php|wp-|sitemap|robots|update_weights)"
    replacement: "/404"
    permanent: false

