apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "awroberts.fullname" . }}-gateway
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    "helm.sh/resource-policy": keep

spec:
  gatewayClassName: {{ .Values.gateway.className }}

  listeners:
    # HTTPS for root domain
    - name: {{ .Values.traefik.entrypoints.websecure.name }}
      protocol: HTTPS
      port: {{ .Values.traefik.entrypoints.websecure.port }}
      hostname: {{ .Values.gateway.hostnames.root | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.traefik.tls.secretName }}
      allowedRoutes:
        namespaces:
          from: All

    # HTTPS for wildcard subdomains
    - name: {{ .Values.traefik.entrypoints.websecure.name }}
      protocol: HTTPS
      port: {{ .Values.traefik.entrypoints.websecure.port }}
      hostname: {{ .Values.gateway.hostnames.wildcard | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.traefik.tls.secretName }}
      allowedRoutes:
        namespaces:
          from: All

    # HTTP listener
    - name: {{ .Values.traefik.entrypoints.web.name }}
      protocol: HTTP
      port: {{ .Values.traefik.entrypoints.web.port }}
      allowedRoutes:
        namespaces:
          from: All
