apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "no-referrer-when-downgrade"
    permissionsPolicy: "geolocation=(), microphone=(), camera=()"
