apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "awroberts.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.io/address-pool: awroberts-pool
spec:
  gatewayClassName: traefik

  addresses:
    - type: IPAddress
      value: {{ .Values.traefik.loadBalancerIP }}

  listeners:
    - name: https-root
      protocol: HTTPS
      port: 443
      hostname: "awroberts.co.uk"
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.traefik.tls.secretName }}
            namespace: {{ .Release.Namespace }}

    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "*.awroberts.co.uk"
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.traefik.tls.secretName }}
            namespace: {{ .Release.Namespace }}

    - name: http
      protocol: HTTP
      port: 80
