apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "awroberts.fullname" . }}-background
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https-root
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https-wildcard
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: http

  hostnames:
    - awroberts.co.uk

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.stream.pathPrefix | default "/stream" }}

      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: no-cache-hls

      backendRefs:
        - name: {{ include "awroberts.fullname" . }}-gateway
          port: 80
