apiVersion: v1
kind: Service
metadata:
  name: {{ include "awroberts.fullname" . }}-background
spec:
  type: ClusterIP
  selector:
    app: {{ include "awroberts.fullname" . }}-background
  ports:
    - port: 80
      targetPort: 80

