apiVersion: v1
kind: Service
metadata:
  name: {{ include "awroberts.fullname" . }}-background
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: {{ include "awroberts.fullname" . }}-background
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: http
      port: 80
      targetPort: 80
