apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.fullname" . }}-background
  labels:
    app: {{ include "awroberts.fullname" . }}-background
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "awroberts.fullname" . }}-background
  template:
    metadata:
      labels:
        app: {{ include "awroberts.fullname" . }}-background
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.backgroundVideo.nginx.image.repository }}:{{ .Values.backgroundVideo.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.backgroundVideo.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80

          volumeMounts:
            - name: media-volume
              mountPath: {{ .Values.backgroundVolume.mountPath }}

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            {{- toYaml .Values.backgroundVideo.resources.nginx | nindent 12 }}

      volumes:
        - name: media-volume
          hostPath:
            path: {{ .Values.backgroundVolume.hostPath }}
            type: DirectoryOrCreate
