apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.fullname" . }}-background
  labels:
    app: {{ include "awroberts.fullname" . }}-background
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "awroberts.fullname" . }}-background
  template:
    metadata:
      labels:
        app: {{ include "awroberts.fullname" . }}-background
    spec:
      containers:
        - name: background-video
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: media-volume
              mountPath: /usr/share/nginx/html/media
      volumes:
        - name: media-volume
          hostPath:
            path: {{ .Values.volume.hostPath }}
            type: DirectoryOrCreate
