apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.fullname" . }}-background-ffmpeg
  labels:
    app: {{ include "awroberts.fullname" . }}-background-ffmpeg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "awroberts.fullname" . }}-background-ffmpeg
  template:
    metadata:
      labels:
        app: {{ include "awroberts.fullname" . }}-background-ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: "{{ .Values.backgroundVideo.ffmpeg.image.repository }}:{{ .Values.backgroundVideo.ffmpeg.image.tag }}"
          imagePullPolicy: {{ .Values.backgroundVideo.ffmpeg.image.pullPolicy }}

          command:
            - /bin/sh
            - -c
            - |
              SOURCE="{{ .Values.backgroundVideo.source }}";
              OUTPUT_DIR="{{ .Values.backgroundVideo.hls.outputDir }}";

              ffmpeg -re -stream_loop -1 -i "$SOURCE" \
                -c:v libx264 -preset veryfast -tune zerolatency \
                -c:a aac -ar 44100 -b:a 128k \
                -f hls \
                -hls_time {{ .Values.backgroundVideo.hls.segmentDuration }} \
                -hls_list_size {{ .Values.backgroundVideo.hls.liveWindow }} \
                -hls_flags delete_segments+append_list \
                -hls_segment_filename "$OUTPUT_DIR/{{ .Values.backgroundVideo.hls.liveSegmentPrefix }}%05d.ts" \
                "$OUTPUT_DIR/index.m3u8"

          volumeMounts:
            - name: media-volume
              mountPath: {{ .Values.backgroundVolume.mountPath }}

          resources:
            {{- toYaml .Values.backgroundVideo.resources.ffmpeg | nindent 12 }}

      volumes:
        - name: media-volume
          hostPath:
            path: {{ .Values.backgroundVolume.hostPath }}
            type: DirectoryOrCreate
