apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awroberts.fullname" . }}-background
  labels:
    app: {{ include "awroberts.fullname" . }}-background
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "awroberts.fullname" . }}-background
  template:
    metadata:
      labels:
        app: {{ include "awroberts.fullname" . }}-background
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.backgroundVideo.image.repository }}:{{ .Values.backgroundVideo.image.tag }}"
          imagePullPolicy: {{ .Values.backgroundVideo.image.pullPolicy }}
          ports:
            - containerPort: 80

          volumeMounts:
            - name: media-volume
              mountPath: /var/www/html/awroberts/awroberts-media

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

      volumes:
        - name: media-volume
          hostPath:
            path: {{ .Values.backgroundVideo.volume.hostPath }}
            type: DirectoryOrCreate
