logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json

additionalArguments:
  - "--api.dashboard=true"
  - "--ping=true"
  - "--entryPoints.web.address=:8000"
  - "--entryPoints.websecure.address=:8443"
  - "--providers.kubernetesgateway"

gateway:
  enabled: true

rbac:
  enabled: true

hostNetwork: true

ports:
  web:
    port: 8000
    hostPort: 8000
    expose:
      default: true
    exposedPort: 8000

  websecure:
    port: 8443
    hostPort: 8443
    expose:
      default: true
    exposedPort: 8443

  traefik:
    port: 9000
    hostPort: 9000
    expose:
      default: false

  metrics:
    port: 9001
    hostPort: 9001
    expose:
      default: false

service:
  enabled: true
  type: ClusterIP
