logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json

additionalArguments:
  - "--entryPoints.websecure.forwardedHeaders.insecure=true"
  - "--entryPoints.web.forwardedHeaders.insecure=true"

providers:
  kubernetesGateway:
    enabled: true

service:
  type: ClusterIP

