logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json

additionalArguments:
  - "--entryPoints.traefik.address="
  - "--entryPoints.metrics.address="
  - "--entryPoints.web.address=:8080"
  - "--entryPoints.websecure.address=:8443"
  - "--entryPoints.web.forwardedHeaders.insecure=true"
  - "--entryPoints.websecure.forwardedHeaders.insecure=true"
  - "--providers.kubernetesgateway=true"

gateway:
  enabled: true

hostNetwork: true

podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true

ports:
  traefik: {}
  metrics: {}

  web:
    port: 8080
    expose:
      default: true
    exposedPort: 80

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443

service:
  enabled: true
  type: ClusterIP
