apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - service.yaml

patches:
  - path: svc-nodeport-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
