let bgVideo;
let curwenFont;
let emailText = 'info@awroberts.co.uk';
let emailSize;
let emailY = 40;
let isHoveringEmail = false;

// deployment JSON
let diag;

function preload() {
  curwenFont = loadFont('/awroberts-media/CURWENFONT.ttf');

  // Load deployment.json generated by kubernetes deployment script
  diag = loadJSON('/deployment.json');
}

function setup() {
  pixelDensity(1);

  const canvas = createCanvas(windowWidth, windowHeight);
  canvas.parent('canvas-container');
  canvas.style('position', 'absolute');
  canvas.style('top', '0');
  canvas.style('left', '0');
  canvas.style('z-index', '1');

  bgVideo = createVideo('/awroberts-media/background.mp4', () => {
    bgVideo.volume(0);
    bgVideo.attribute('muted', '');
    bgVideo.attribute('playsinline', '');
    bgVideo.attribute('autoplay', '');
    bgVideo.loop();
    bgVideo.play();
  });

  bgVideo.hide();

  emailSize = constrain(min(windowWidth, windowHeight) * 0.1, 24, 140);
  textFont(curwenFont);
  textSize(emailSize);
  textAlign(CENTER, TOP);
}

function draw() {
  clear();
  image(bgVideo, 0, 0, width, height);

  drawEmail();
  drawDeploymentInfo();
}

function drawEmail() {
  let totalWidth = textWidth(emailText);
  let xStart = width / 2 - totalWidth / 2;
  let yStart = emailY;
  let buffer = 20;

  isHoveringEmail =
    mouseX > xStart - buffer &&
    mouseX < xStart + totalWidth + buffer &&
    mouseY > yStart - buffer &&
    mouseY < yStart + emailSize + buffer;

  if (isHoveringEmail) {
    fill(255, 220, 180);
    textSize(emailSize * 1.05);
    cursor(HAND);
  } else {
    fill(255);
    textSize(emailSize);
    cursor(ARROW);
  }

  text(emailText, width / 2, emailY);
}

// draw deployment.json values
function drawDeploymentInfo() {
  if (!diag) return;

  textAlign(LEFT);
  textSize(32);
  fill(255);

  // Bottom-left anchor
  const margin = 40;
  let x = margin;
  let y = height - margin;

  // Build lines from bottom upward
  const lines = [
    `SHA: ${diag.build.sha}`,
    `Image Tag: ${diag.build.imageTag}`,
    `Image: ${diag.deployment.image}`,
    `Pod IP: ${diag.pod.ip}`,
    `Pod Status: ${diag.pod.status}`,
    `Pod: ${diag.pod.name}`,
    `Service ClusterIP: ${diag.service.clusterIP}`,
    `Deployment: ${diag.deployment.name}`
  ];

  // Draw from bottom to top
  for (let i = lines.length - 1; i >= 0; i--) {
    text(lines[i], x, y);
    y -= 40; // line spacing
  }
}


function mousePressed() {
  if (isHoveringEmail) {
    window.location.href = 'mailto:info@awroberts.co.uk';
  }
}

function touchStarted() {
  if (touches.length > 0) {
    let tx = touches[0].x;
    let ty = touches[0].y;

    let totalWidth = textWidth(emailText);
    let xStart = width / 2 - totalWidth / 2;
    let yStart = emailY;

    if (tx > xStart && tx < xStart + totalWidth &&
        ty > yStart && ty < yStart + emailSize) {
      window.location.href = 'mailto:info@awroberts.co.uk';
    }
  }
  return false;
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
  bgVideo.size(width, height);

  emailSize = constrain(min(windowWidth, windowHeight) * 0.1, 24, 140);
  textSize(emailSize);
}
