apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namePrefix }}-speaker
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.namePrefix }}-speaker
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namePrefix }}-speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}-speaker
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}-speaker
  namespace: metallb-system
