controller:
  frr:
    enabled: false

speaker:
  frr:
    enabled: false
  containerSecurityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
    runAsUser: 0
    runAsNonRoot: false

bgp:
  enabled: false

layer2:
  enabled: true
