namePrefix: "awroberts"

frr:
  enabled: false

speaker:
  enabled: true
  hostNetwork: true
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  frr:
    enabled: false
  config:
    interfaces:
      - enp1s0

frrk8s:
  enabled: false

ipRange:
  start: "192.168.1.150"
  end: "192.168.1.160"
