namePrefix: "awroberts"

interface: "enp1s0"

frr:
  enabled: false

speaker:
  enabled: true
  daemonset:
    hostNetwork: false
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  frr:
    enabled: false

ipRange:
  start: "192.168.1.150"
  end: "192.168.1.160"

frrk8s:
  enabled: false
